adminpanel/urls.py
# """adminpanel URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
import report_builder
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('salon.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'salon'


urlpatterns = (
    # path('admin/', admin.site.urls),
     path("", views.welcome, name="welcome"),
     path("login/", views.login, name="login"),
     path("logout/", views.logout, name="logout"),
     path("index/", views.indexs, name="index"),
     path("about/", views.abouts, name="abouts"),
     path("profile/", views.profile, name="profile"),
     path("product/<int:pk>/", views.product, name="product"),
     path("register/", views.register, name="register"),
     path("package/", views.packser, name="package"),
     # path("package/<int:no>",views.totalPack,name="package"),
     path("barbers/", views.specialist, name="specialist"),
     path("service/", views.service, name="service"),
     path("servicedisplay/<int:no>/", views.servicedisplay, name="servicedisplay"),
     path("servicecategory/", views.service_cat, name="servicecategory"),
     path("Productcategory/", views.prodcat, name="Productcategory"),
     path("contact/<int:pk>/", views.contact, name="contact"),
     path("Gallery/", views.Gallery, name="Gallery"),
     path("appointment/", views.appointment, name="appointment"),
     path("appointmenttake/<int:pk>/", views.appointmenttake, name="appointmenttake"),
     path("appointPackage/<int:pk>/", views.packappointment, name="appointPackage"),
     path("appointmentcancel/", views.appointmentCancel, name="appointment"),
     path("appointmentchange/<int:pk>/", views.appointmentchange, name="appointment"),
     path("cart/", views.addTocart, name="cart"),
     path("cartdetails/", views.addTocarts, name="cartdetails"),
     path("removecart/<int:no>/", views.removecart, name="removecart"),
     path("mail/", views.mail, name="mail"),
     path('change_password/', views.change_password, name='change_password'),
     # path("feedback/", views.feedback, name="feed_save"),
     path("tmp/<int:no>/", views.tmp, name="tmp"),
     path("checkout/", views.checkout, name="checkout"),
     # path("checkout/",views.orders, name="checkout"),
     path("membership/", views.membership, name="membership"),
     path("takemembership/<int:no>/", views.takemembership, name="takemembership"),
     path("orderdetails/", views.orderdetails, name="orderdetails"),
     path("invoice/<int:no>/", views.invoice, name="invoice"),
     # path("invoicepdf/", views.render_to_pdf, name="invoicepdf"),
     path("serviceinvoice/<int:no>/", views.serviceInvoice,name="Sinvoice"),
     path("report/appointment_status/<int:no>",views.AppointmentReport, name="report"),
     path("salesReport/<int:no>",views.SalesOrderReport, name="salesReport"),
     path("specialistReport/<int:no>",views.specialistReport, name="specialistReport"),


)

salon/forms.py
from django import forms
from .models import Appointment,Specialist,AuthUser

class Appoint(forms.ModelForm):
    specialist_id = forms.ModelChoiceField(queryset= Specialist.objects.all(), label="Post", widget=forms.RadioSelect(), initial=0)
    class Meta:
        model = Appointment
        fields = ["specialist_specialist","auth_user"]

salon/views.py
from datetime import *
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect, render_to_response
from django.http import Http404, HttpResponse,FileResponse
from django.template.loader import get_template, render_to_string
from django.template import loader, Template,Context
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.units import inch, mm

from .models import Salon, ServiceCategories, Appointment, Specialist, AuthUser, Gallary, Services, Product, Cart, SalesDetail, Offers, Feedback, ProductCategories, Package, Packageservices, Sales, ServiceGiven, MembershipType
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.core.mail import send_mail
import pdfkit as pdf

from suit_dashboard.views import DashboardView
from suit_dashboard.views import DashboardView

class HomeView(DashboardView):
    pass

def indexs(request):
    # if request.user.is_authenticated == True:
    feed = Feedback.objects.all()
    return render(request, "salon/index.html", {'feedback': feed})


def service(request):
    # ser_cat = ServiceCategories.objects.filter(service_categories_service_categories_no=ServiceCategories.objects.service_categories_no)
    ser_cat = Services.objects.all()
    # service =Services.objects.all()
    # offers = Offers.objects.all()
    # if request.method == "POST":
    #     service_name = request.POST['service_name']
    #     service_url = request.POST['service_url']
    #     service_dur = request.POST['service_duration']
    #     rate = request.POST['service_rate']
    # #     # services_service = ServiceCategories.objects.get(service_categories_no=int(request.POST['service_categories_name']))
    #     ser_cat = ServiceCategories.objects.filter(service_categories_service_categories_no=int(request.POST['service_categories_no']))
    #     # services_service = ServiceCategories.objects.all().filter(service_categories_service_categories_no=request.POST['service_categories_no'])
    #     offer = Offers.objects.get(offer_id=request.POST['offer_id'])
    #     ser = Services(service_name=service_name, service_url=service_url, service_duration=service_dur, service_rate=rate,service_categories_service_categories_no=services_service, offer_offer=offer)
    #     ser.save()
    return render(request, "salon/service.html", {'service': ser_cat})


def service_cat(request):
    ser_cat = ServiceCategories.objects.all()
    # service= Services.objects.all().filter(service_categories_service_categories_no= int(request.POST['service_categories_name']))
    # #template = loader.get_template('salon/index.html')
    return render(request, "salon/servicecategory.html", {"ser_cat": ser_cat})


def servicedisplay(request, no):
    # service = ServiceCategories.objects.get(service_categories_no=int(request.POST['service_categories_name']))
    # id=int(ServiceCategories.objects.get(service_categories_no=int(request.POST['service_categories_name'])))
    # service= service_cat.GET.get('service_categories_no')
    no = ServiceCategories.objects.get(service_categories_no=no)
    ser_cat = Services.objects.filter(service_categories_service_categories_no=no)
    print(ser_cat)
    return render(request, "salon/servicedisplay.html", {'ser_cat': ser_cat, 'pk': no})


def abouts(request):
    return render(request, "salon/about.html")


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('/login/')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'salon/change_password.html', {'form': form})


def prodcat(requset):
    prod = ProductCategories.objects.all()
    return render(requset, "salon/Productcategory.html", {'prod': prod})


def product(request, pk):
    p = ProductCategories.objects.get(product_categories_id=pk)
    products = Product.objects.filter(product_categories_product_categories=p)
    feedbck = Feedback.objects.filter(product_product=products)
    return render(request, "salon/product.html", {'products': products,'feedback':feedbck})


def logout(request):
    auth.logout(request)
    return redirect('salon:login')


def login(request):
    # authuser= AuthUser.objects.all()
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        # user.profile.role='is_superuser'

        if user is not None:
            auth.login(request, user)
            usrObj = AuthUser.objects.get(username=user.username)
            if usrObj.is_staff:
                # print("Login succesfully")
                # messages.info(request, "Login Succesfully")
                return redirect('/admin/')
            else:
                return redirect('/index/')
        else:
            messages.info(request, "Invalid username or password")
            return redirect("/login/")
    else:
        return render(request, "salon/login.html")

@login_required()
def appointment(request):
    specialists = Specialist.objects.all()
    authUser = AuthUser.objects.all()
    services = Services.objects.all()
    if request.method == "POST":
        appointment_date = request.POST['appointment_date']
        appointment_time = request.POST['appointment_time']
        # appointment_status = request.POST['appointment_status']
        services_service = Services.objects.get(service_id=int(request.POST['service_name']))
        # print(services_service.service_id)
        specialist_specialist = Specialist.objects.get(specialist_id=int(request.POST['specialist_name']))
        auth_user = AuthUser.objects.get(id=int(request.POST['username']))
        apt = Appointment(appointment_date=appointment_date, appointment_time=appointment_time,
                          services_service=services_service, appointment_status=1,
                          specialist_specialist=specialist_specialist, auth_user=auth_user)
        apnt = Appointment.objects.filter(appointment_date=appointment_date,appointment_time=appointment_time,specialist_specialist=specialist_specialist)
        if len(apnt) > 0:
            return HttpResponse("This appointment time already taken")
        else:
            apt.save()
            services_service = Services.objects.get(service_id=int(request.POST['service_name']))
            user_email = AuthUser.objects.get(id=request.user.id)
            datee = appointment_date  # Appointment.objects.filter(appointment_id=(request.POST['appointment_date']))
            time = appointment_time
            print(time)
            print(services_service)
            subject = "OWNER OF KALLISTAA"
            msg = "Dear customer your appointment for " + str(
                services_service) + " is booked on " + datee + " at " + time
            to = user_email.email
            res = send_mail(subject, msg, settings.EMAIL_HOST_USER, [to])

            if (res == 1):
                msg = "Mail Sent Successfuly"
            else:
                msg = "Mail could not sent"
            print(msg)

        # if apnt.appointment_date == appointment_date:
        #     if apnt.appointment_time == appointment_time and apnt.specialist_specialist == specialist_specialist:
        #         return HttpResponse("This appointment time already taken")
        # else:
        #     apt.save()

        print("Appointment Booked")
        print("Service Given is called")
        # ser_book = ServiceGiven()
        # ser_book.service_date = appointment_date
        # ser_book.amount = services_service.service_rate
        # ser_book.appointment_appointment = apt
        # ser_book.auth_user = AuthUser.objects.get(id=request.user.id)
        # ser_book.package_package = Package.objects.get(package_id=1)  # int(request.POST['packid']
        # ser_book.save()
        print("Service given is confirmed")
    return render(request, 'salon/appointment.html',
                  {'ser_cat': services, 'specialist': specialists, 'authUser': authUser})


# def serviceBOOk(request,pk):
#     ser_book = ServiceGiven.objects.all()
#     id = Appointment.objects.filter(auth_user=request.user.id)
#     ser_book.service_date = id.appointment_date
#     ser_book.amount = id.services_service.service_rate
#     ser_book.appointment_appointment = ServiceGiven.objects.get(appointment_appointment=pk)
#     ser_book.package_package = 1
#     ser_book.save()
#     return HttpResponse("Service is Given to the customer")


@login_required()
def appointmenttake(request, pk):
  try:
    no = Services.objects.get(service_id=pk)
    ser_cat = Appointment.objects.filter(services_service=no)
    specialists = Specialist.objects.all()
    packages = Package.objects.all()
    authUser = AuthUser.objects.all()
    if request.method == "POST":
        appointment_date = request.POST['appointment_date']
        appointment_time = request.POST['appointment_time']
        # appointment_status = request.POST['appointment_status']
        services_service = no  # Services.objects.get(service_id=int(request.POST['service_name']))
        specialist_specialist = Specialist.objects.get(specialist_id=int(request.POST['specialist_name']))

salon/templates/salon/addspecialist.html
{% load static%}
<!DOCTYPE html>
<head>
	<title> Add specialist</title>
	<link rel="stylesheet" href="{%static 'css/specialist.css'%}">
</head>
<body id="spe">
	
	<form class="box" method ="post">
		<h1>Add Specialist Details</h1>
		<input type="text" name="specialist-id" placeholder="specialist_id" bgcolor="red"><br>
		<input type="text" name="" placeholder="specialist_name"><br>
		<input type="boolean" name="" placeholder="gender"><br>
		<input type="digits" name="" placeholder="contact-no."><br>
		<input type="submit" value="ADD" >
		<input type="submit" value="UPDATE" >
		<input type="submit" value="DELETE" >
	</form>
</body>

salon/templates/salon/change_password.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'css/changepassword.css'%}">
    <title>Change Password</title>
</head>
<body>
    <form class="box" action="" method="post">
			{% csrf_token %}
	   <h1>Change password</h1>
<!--	   <input type="password" name="password" placeholder="Old Password"><br>-->
<!--       <input type="password" name="password" placeholder="New Password"><br>-->
<!--	   <input type="submit" value="Login">-->
        <div>
            {{ form }}
        {% if messages %}
          <ul class="messages">
              <li class="{{ message.tags }}">{{ message }}</li>
          </ul>
        {% endif %}
            <input type="submit" name="Save">
		</div>
	</form>
</body>
</html>

salon/templates/salon/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
	<meta charset="utf-8">
	<title>Animated login Form</title>
	<link rel="stylesheet" href="{%static 'css/logincss.css'%}">
   </head>
   <body style="background-image:url('/static/images/bg.png');" >
	<form class="box" action="" method="post">
		{% csrf_token %}
<!--	   <h1>Login</h1>-->
<!--	   <input type="text" name="username" placeholder="Username"><br>-->
<!--	   <input type="password" name="password" placeholder="Password"><br>-->
<!--	   <input type="submit" value="Login">-->

<!--		<a href="\register\">New User?Clickhere</a><br>-->
<!--		<a href="\password_reset\">Forgot Password?Click here</a>-->
<!--		<div id="box">-->
<!--			{%for message in messages%}-->
<!--			<h3>{{message}}</h3>-->
<!--			{%endfor%}-->
<!--		</div>-->
<!--	</form>-->

				<div class="loginbox">
					<img src="{% static 'images/avatar.png' %}" width="120" class="avatar">
					<h1>Login Here</h1>
						 <p>Username</p>
						 <input type="text" name="username" placeholder="Username"><br><br>
						 <p>Password</p>
	  					 <input type="password" name="password" placeholder="Password"><br><br>
						 <input type="submit" name="" value="Login"><br>
						 <a href="\register\"><h3>New User?Clickhere</h3></a>
<!--					<a href="\password_reset\"><h3>Forgot Password?Click here</h3></a>-->

						<div id="box">
							{%for message in messages%}
							<h3>{{message}}</h3>
							{%endfor%}
						</div>

				</div>
	</form>
   </body>
</html>

salon/templates/salon/product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Site Metas -->
    <title>KALLISTAA</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Colors CSS -->
    <link rel="stylesheet" href="{% static 'css/colors.css' %}">
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="{% static 'css/versions.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/prettyPhoto.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/loading.css' %}">
    <link rel="stylesheet" href="{% static 'css/qty.css' %}">
<!--    <link rel="stylesheet" href="{% static 'css/qtycounter.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="{%static 'js/angular.min.js'%}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        #line{
            background:white;
            border:0;
        }


    </style>
</head>

<body class="barber_version" ng-app="myApp" ng-controller="myCtrl">

<!-- LOADER -->
<div id="preloader">
    <div class="cube-wrapper">
        <div class="cube-folding">
            <span class="leaf1"></span>
            <span class="leaf2"></span>
            <span class="leaf3"></span>
            <span class="leaf4"></span>
        </div>
        <span class="loading" data-name="Loading">KALLISTAA Loading</span>
    </div>
</div><!-- end loader -->
<!-- END LOADER -->

<div id="wrapper">

    <!-- Sidebar-wrapper -->
    <div id="sidebar-wrapper">
        <div class="side-top-left">
            <div class="logo-sidebar">
                <a href="\index\"><img src="{%static 'images/logos/logo.png'%}" width="285" alt="image"></a>
            </div>
            <ul class="sidebar-nav">
                <li class="dropdown">

                    <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i
                            class="fa fa-fw fa-user"></i><b> {{user.username}} </b><i class="fa fa-fw fa-caret"></i><i
                            class="fa fa-angle-down"></i></a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                        <li>
                            <a tabindex="-1" href="\profile\" class="btn btn-light btn-radius btn-brd grd1 effect-1">Profile</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a tabindex="-1" href="\logout\" class="btn btn-light btn-radius btn-brd grd1 effect-1">Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a tabindex="-1" href="\login\" class="btn btn-light btn-radius btn-brd grd1 effect-1">Sign
                                in</a>
                        </li>
                        <li>
                            <a tabindex="-1" href="\register\" class="btn btn-light btn-radius btn-brd grd1 effect-1">Sign
                                Up</a>
                        </li>
                        {%endif%}
                    </ul>
                </li>
            </ul>

            <!--        </div>-->
            <ul class="sidebar-nav">
                <li><a href="\index\" >Home</a></li>
                <li><a href="\about\">About Us</a></li>
                <li><a href="\appointment\">Appointment</a></li>
                <li><a href="\barbers\">Our Specialist</a></li>
                <li><a href="\servicecategory\">Our Services Categories</a></li>
                <li><a href="\membership\">Our Membership</a></li>
                <li><a href="\package\">Our Packages</a></li>
                <li><a href="\Gallery\">Gallery</a></li>
                <li><a href="\Productcategory\"  class="active">Our Product Categories</a></li>
                <li><a href="\cartdetails\" class="nav-cart-icon nav-sprite">Add to Cart</a></li>
            </ul>

        </div>
    </div>
    <!-- End Sidebar-wrapper -->
    <div class="section lb">
        <div class="container-fluid">
            <div class="section-title row text-center">
                <div class="col-md-8 col-md-offset-2">
                    <h3>OUR PRODUCTS</h3>
                    <hr class="grd1">
                    <small>VISIT OUR PRODUCTS </small>
                    <p class="lead">
                        ....................................................................................................................</p>
                </div>
            </div>
        </div>
        <!-- Page Content -->

        <div id="page-content-wrapper">
            <div class="container">
                {% for i in products%}

                <div class="row dev-list text-center">
                    <div >
                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <div class="widget clearfix">
                                <div class="post-media wow fadeIn">

                                    <!--                                   class="hoverbutton global-radius"><i class="flaticon-unlink"></i></a>-->
                                    <img src="{{i.product_url.url}}" alt="Not found" height="250" width="75">
                                    <!--                                </div>-->
                                    <div>
                                        <h4><B>{{i.product_name}}</B></h4>
                                    </div>
                                    <h4>Price <i class="fa fa-rupee"></i> {{i.product_price}}</h4>
                                    <h4>Description</h4>
                                    <textarea style="resize: none;" disabled id="line" class="post-media">{{i.product_desc}}</textarea>
                                    <form action="{% url 'salon:cart' %}" method="post">
                                        {% csrf_token %}
                                        <input type="number" name="pid" value="{{i.product_id}}" hidden>
                                        
                                        <div class="sp-quantity">
                                            <div class="sp-minus fff"> <a class="ddd" href="#">-</a></div>
                                            <div class="sp-input">
                                                <input type="text" class="quntity-input" name="qty" value="1">
                                            </div>
                                            <div class="sp-plus fff"> <a class="ddd" href="#">+</a></div>
                                        </div>

                                        <button class="btn" type="submit">Add to Cart</button>
                                    </form>
                                </div><!-- end service -->
                            </div>
                        </div>
                    </div>

                    {% endfor%}
                </div>
            </div>
        </div>
    </div>
   
    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'js/all.js' %}"></script>
    <script src="{% static 'js/responsive-tabs.js'%}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/qtycounter.js'%}"></script>
    <script src="{% static 'https://code.jquery.com/jquery-3.4.1.slim.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- Menu Toggle Script -->
    <script>
    (function($) {
        "use strict";
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
        smoothScroll.init({
            selector: '[data-scroll]', // Selector for links (must be a class, ID, data attribute, or element tag)
            selectorHeader: null, // Selector for fixed headers (must be a valid CSS selector) [optional]
            speed: 500, // Integer. How fast to complete the scroll in milliseconds
            easing: 'easeInOutCubic', // Easing pattern to use
            offset: 0, // Integer. How far to offset the scrolling anchor location in pixels
            callback: function ( anchor, toggle ) {} // Function to run after scrolling
        });
    })(jQuery);

    $(".ddd").on("click", function () {

    var $button = $(this),
        $input = $button.closest('.sp-quantity').find("input.quntity-input");
    var oldValue = $input.val(),
        newVal;

    if ($.trim($button.text()) == "+") {
        newVal = parseFloat(oldValue) + 1;
    } else {
        // Don't allow decrementing below zero
        if (oldValue > 0) {
            newVal = parseFloat(oldValue) - 1;
        } else {
            newVal = 0;
        }
    }

    $input.val(newVal);

    });


    </script>

</body>
</html>

salon/templates/salon/thankyoupage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquerymain.js' %}"></script>
    <title>Title</title>
</head>
<body>
<div class="jumbotron text-center">
  <h1 class="display-3">Thank You!</h1>
  <p class="lead"><strong>Please check your email</strong> for further instructions on how to complete your account setup.</p>
  <hr>
  <p>
    Having trouble? <a href="\contact\">Contact us</a>
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="\index\" role="button">Continue to homepage</a>
  </p>
    <p class="lead"><a href="\invoice\{{saleid}}">View Invoice</a></p>
</div>
</body>
</html>

salon/templates/salon/welcome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>KALLISTAA</title>
      <link rel="stylesheet" href="{% static 'css/welcome.css' %}">
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>-->
</head>
<body>
<!--<div class="container" style="background-image:url('/static/images/welcomelogo.png');">-->
<!--&lt;!&ndash;       <div class="btn">&ndash;&gt;-->

<!--       </div>-->

<div class="container">
  <img src="{% static 'images/welcomelogo.jpg' %}" width="1520" height="730">
    <button class="btn"><a href="\index\"><font color="white"> Visit us</font></a></button>
    <div class="centered"><font color="white"><b>WELCOME TO KALLISTAA</b></font></div>
</div>

</body>
</html>